name: GiantSwarm Test Catalog Cleanup
on:
  schedule:
    - cron: '38 0 1 * *'
  workflow_dispatch:
jobs:
  cleanup:
    uses: giantswarm/app-catalog-cleanup-tool/.github/workflows/cleanup.yaml@main
    with:
      delete-before: "2 weeks"
      dry-run: false
